---
- name: Install nfs-kernel-server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Create exports directory
  ansible.builtin.file:
    path: /srv/nomad
    state: directory
    mode: "0777"

- name: Copy nfs config
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    mode: "0644"
  notify: Apply exports

- name: Start nfs server
  ansible.builtin.systemd:
    name: nfs-server
    state: started
    enabled: true
