---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Create HAProxy certs
  ansible.builtin.import_role:
    name: certs_ownca
  vars:
    certs_dir: /opt/haproxy/tls
    owner: haproxy
    alt_names:
      - 'DNS:*.{{ external_domain }}'
      - 'DNS:*.{{ apps_subdomain }}.{{ external_domain }}'

- name: Rename HAProxy private key
  ansible.builtin.copy:
    remote_src: true
    src: /opt/haproxy/tls/key.pem
    dest: /opt/haproxy/tls/cert.pem.key
    owner: haproxy
    group: haproxy
    mode: "0600"

- name: Copy HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    mode: "0600"
  notify: Restart HAProxy
