---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Create HAProxy certs
  ansible.builtin.import_role:
    name: certs_ownca
  vars:
    certs_dir: /etc/certs.d
    owner: haproxy
    agent_name: haproxy
    alt_names:
      - 'DNS:*.{{ external_domain }}'
      - 'DNS:*.{{ apps_subdomain }}.{{ external_domain }}'

- ansible.builtin.set_fact:
    certs_dir: /opt/haproxy/tls

- name: Create HAProxy client certs and setup consul-template
  ansible.builtin.import_role:
    name: certs_consul_template
  vars:
    templates_dir: /opt/haproxy/templates
    certs_dir: /opt/haproxy/tls
    common_name: 'haproxy.{{ external_domain }}'
    service_name: haproxy
    owner: haproxy

- name: Copy HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    mode: "0600"
  notify: Restart HAProxy
