---
# Required variables
#   - policy_name
#   - policy_rules
#   - token_file

- name: Read Consul management token
  ansible.builtin.set_fact:
    consul_management_token: '{{ lookup("file", ".tmp/root_token_consul.txt") }}'

- name: 'Define accessor id {{ ansible_hostname }}'
  ansible.builtin.set_fact:
    accessor_id: '{{ (ansible_hostname + ".token.service.consul") | to_uuid(namespace="6ba7b810-9dad-11d1-80b4-00c04fd430c8") }}'

- name: 'Check Consul policy {{ ansible_hostname }}'
  run_once: true
  delegate_to: consul-server1
  ansible.builtin.command:
    consul acl policy read -token {{ consul_management_token }} -name {{ policy_name }} -format json
  failed_when: false
  register: check_consul_policy

- name: 'Create Consul acl policy {{ ansible_hostname }}'
  when: check_consul_policy.rc != 0 or check_consul_policy.stdout == "null"
  delegate_to: consul-server1
  run_once: true
  ansible.builtin.command:
    stdin: '{{ policy_rules }}'
    cmd:
      consul acl policy create
        -token {{ consul_management_token }}
        -name {{ policy_name }}
        -format json
        -rules -
  register: consul_acl_policy
  changed_when:
    'consul_acl_policy.rc == 0 and "ID" in consul_acl_policy.stdout'
  failed_when:
    'consul_acl_policy.rc != 0 and "already exists" not in consul_acl_policy.stderr'

- name: 'Check Consul token {{ ansible_hostname }}'
  delegate_to: consul-server1
  ansible.builtin.command:
    consul acl token read
      -token {{ consul_management_token }}
      -accessor-id {{ accessor_id }}
      -format json
  register: check_consul_token
  failed_when: false

- name: 'Create Consul token {{ ansible_hostname }}'
  when: check_consul_token.rc != 0
  block:
    - name: 'Create Consul token {{ ansible_hostname }}'
      delegate_to: consul-server1
      ansible.builtin.command:
        cmd:
          consul acl token create
            -token {{ consul_management_token }}
            -accessor {{ accessor_id }}
            -description '{{ ansible_hostname }} service token'
            -policy-name {{ policy_name }}
            -format json
      register: consul_acl_token_result
      changed_when: consul_acl_token_result.rc == 0

    - name: 'Read Consul token {{ ansible_hostname }}'
      ansible.builtin.set_fact:
        consul_token: '{{ "SecretID" | extract(consul_acl_token_result.stdout | from_json) }}'

- name: 'Read Consul token {{ ansible_hostname }}'
  when: check_consul_token.rc == 0
  ansible.builtin.set_fact:
    consul_token: '{{ "SecretID" | extract(check_consul_token.stdout | from_json) }}'

- name: 'Save Consul token {{ ansible_hostname }}'
  ansible.builtin.copy:
    content: '{{ consul_token }}'
    dest: '{{ token_file }}'
    mode: 0640
