---
- name: install traefik
  unarchive:
    src: "{{ traefik_url }}"
    remote_src: yes
    dest: /usr/local/bin/
    mode: 0755
    include:
      - traefik

- name: create traefik service
  copy:
    src: traefik.service
    dest: /etc/systemd/system/

- name: create traefik config directory
  file:
    path: /etc/traefik
    state: directory

- name: copy traefik config
  template:
    src: traefik.yaml.j2
    dest: /etc/traefik/traefik.yaml
  register: traefik_config

- name: create traefik file provider directory
  file:
    path: /etc/traefik/conf
    state: directory

- name: copy traefik file provider config
  template:
    src: nomad.yaml.j2
    dest: /etc/traefik/conf/nomad.yaml
  register: traefik_provider_config

- name: start traefik
  when: traefik_config.changed or traefik_provider_config.changed
  service:
    name: traefik
    state: restarted
    enabled: yes
