---
- name: install traefik
  unarchive:
    src: "{{ traefik_url }}"
    remote_src: yes
    dest: /usr/local/bin/
    mode: 0755
    include:
      - traefik

- name: create traefik service
  copy:
    src: traefik.service
    dest: /etc/systemd/system/

- name: create traefik config directory
  file:
    path: /etc/traefik
    state: directory

- name: copy traefik config
  copy:
    src: traefik.toml
    dest: /etc/traefik/traefik.toml
  register: traefik_config

- name: create traefik file provider directory
  file:
    path: /etc/traefik/conf
    state: directory

- name: copy traefik file provider config
  loop:
    - nomad
    - prometheus
  copy:
    src: "{{ item }}.toml"
    dest: /etc/traefik/conf/{{ item }}.toml
  register: traefik_provider_config

- name: start traefik
  when: traefik_config.changed or traefik_provider_config.changed
  service:
    name: traefik
    state: restarted
    enabled: yes
