all:
  hosts:
    nfs-server:    { ansible_host: '10.99.0.200' }
    load-balancer: { ansible_host: '10.99.0.254' }
  children:
    consul_servers:
      hosts:
        consul-server-1: { ansible_host: '10.99.0.11' }
        consul-server-2: { ansible_host: '10.99.0.12' }
        consul-server-3: { ansible_host: '10.99.0.13' }

    vault_servers:
      hosts:
        vault-server-1: { ansible_host: '10.99.0.21' }
        vault-server-2: { ansible_host: '10.99.0.22' }
        vault-server-3: { ansible_host: '10.99.0.23' }

    nomad_servers:
      hosts:
        nomad-server-1: { ansible_host: '10.99.0.31' }
        nomad-server-2: { ansible_host: '10.99.0.32' }
        nomad-server-3: { ansible_host: '10.99.0.33' }

    nomad_clients:
      children:
        nomad_infra_clients:
          hosts:
            nomad-infra-client-1: { ansible_host: '10.99.1.1' }
            nomad-infra-client-2: { ansible_host: '10.99.1.2' }

        nomad_apps_clients:
          hosts:
            nomad-apps-client-1: { ansible_host: '10.99.1.11' }
            nomad-apps-client-2: { ansible_host: '10.99.1.12' }
            nomad-apps-client-3: { ansible_host: '10.99.1.13' }
