all:
  children:
    cluster:
      hosts:
        nfs-server:    { ansible_host: '10.99.0.200' }
        load-balancer: { ansible_host: '10.99.0.254' }
      children:
        consul_servers:
          hosts:
            consul-server1: { ansible_host: '10.99.0.11' }
            consul-server2: { ansible_host: '10.99.0.12' }
            consul-server3: { ansible_host: '10.99.0.13' }

        vault_servers:
          hosts:
            vault-server1: { ansible_host: '10.99.0.21' }
            vault-server2: { ansible_host: '10.99.0.22' }
            vault-server3: { ansible_host: '10.99.0.23' }

        nomad_servers:
          hosts:
            nomad-server1: { ansible_host: '10.99.0.31' }
            nomad-server2: { ansible_host: '10.99.0.32' }
            nomad-server3: { ansible_host: '10.99.0.33' }

        nomad_clients:
          children:
            nomad_infra_clients:
              hosts:
                nomad-infra-client1: { ansible_host: '10.99.0.41' }
                nomad-infra-client2: { ansible_host: '10.99.0.42' }

            nomad_apps_clients:
              hosts:
                nomad-apps-client1: { ansible_host: '10.99.1.1' }
                nomad-apps-client2: { ansible_host: '10.99.1.2' }
                nomad-apps-client3: { ansible_host: '10.99.1.3' }
