---
- name: Bootstrap Nomad acl
  ansible.builtin.command:
    nomad acl bootstrap
      -address=https://localhost:4646
      -client-cert=/etc/certs.d/cert.pem
      -client-key=/etc/certs.d/key.pem
      -t '{{ "{{" }} .SecretID {{ "}}" }}'
  register: acl_bootstrap_result
  changed_when:
    - acl_bootstrap_result.rc == 0
  failed_when:
    - acl_bootstrap_result.rc != 0
    - '"ACL bootstrap already done" not in acl_bootstrap_result.stderr'
  notify: Save Nomad root token
