---
- name: Create nomad clients
  loop: '{{ groups["nomad_infra_clients"] + groups["nomad_apps_clients"] }}'
  community.general.lxd_container:
    name: '{{ hostvars[item].inventory_hostname }}'
    profiles:
      - nomad
    state: started
    wait_for_container: true
    wait_for_ipv4_addresses: true
    source:
      type: image
      mode: local
      alias: nomad-client
    config:
      # cloud-init.user-data: |
      #   #cloud-config
      #   ssh_authorized_keys: ['{{ lookup("file", ".tmp/ssh/id_rsa.pub") }}']
      #   packages: [openssh-server]
      limits.cpu: '1'
      limits.memory: 4GB
      security.nesting: 'true'
      security.privileged: 'true'
      raw.lxc: |-
        lxc.apparmor.profile=unconfined
        lxc.cgroup.devices.allow=a
        lxc.cap.drop=
      cloud-init.network-config: |
        version: 2
        ethernets:
          eth0:
            addresses:
              - {{ hostvars[item].ansible_host }}/16
            routes:
              - { to: default, via: {{ gateway_address }} }
            nameservers:
              addresses: ["9.9.9.9", "149.112.112.112"]
