---
- name: create namespaces
  loop:
    - system-gateway
    - system-storage
    - system-monitoring
    - system-autoscaling
  command: "nomad namespace apply {{ item }}"

- name: create jobs dir
  file:
    path: /opt/jobs
    state: directory

- name: copy proxy job
  template:
    src: proxy.nomad.j2
    dest: /opt/jobs/proxy.nomad
  register: proxy_job

- name: run proxy job
  when: proxy_job.changed
  command: nomad job run -namespace system-gateway /opt/jobs/proxy.nomad

- name: copy autoscaler job
  copy:
    src: autoscaler.nomad
    dest: /opt/jobs/
  register: autoscaler_job

- name: run autoscaler job
  when: autoscaler_job.changed
  command: nomad job run -namespace system-autoscaling /opt/jobs/autoscaler.nomad

- name: copy nfs csi plugin jobs
  copy:
    src: rocketduck-nfs
    dest: /opt/jobs/
  register: nfs_plugin_jobs

- name: run nfs csi plugin jobs
  when: nfs_plugin_jobs and nfs_plugin_jobs.changed
  loop:
    - controller.nomad
    - node.nomad
  command: "nomad job run -namespace system-storage /opt/jobs/rocketduck-nfs/{{ item }}"

- name: copy prometheus job
  copy:
    src: prometheus.nomad
    dest: /opt/jobs/
  register: prometheus_job

- name: run prometheus job
  when: prometheus_job and prometheus_job.changed
  command: nomad job run -namespace system-monitoring /opt/jobs/prometheus.nomad
