---
- name: Read Consul management token and encrypt key
  ansible.builtin.set_fact:
    consul_management_token: '{{ lookup("file", ".tmp/root_token_consul.txt") }}'
    consul_encrypt_key: '{{ lookup("file", ".tmp/encrypt_keys/consul.txt") }}'

- name: Define agent token
  ansible.builtin.set_fact:
    consul_agent_token: '{{ (inventory_hostname + ".agent.consul") | to_uuid(namespace="6ba7b810-9dad-11d1-80b4-00c04fd430c8") }}'

- name: Install Consul
  ansible.builtin.apt:
    name: consul
    state: present
    update_cache: true

- name: Include CA cert
  ansible.builtin.import_role:
    name: ca_cert

- name: Create Consul certs and setup consul-template
  ansible.builtin.import_role:
    name: certs_consul_template
  vars:
    templates_dir: /opt/consul/templates
    certs_dir: /opt/consul/tls
    service_name: consul
    owner: consul
    common_name: server.dc1.consul
    alt_names:
      - server.dc1.consul
      - consul.service.consul
      - 'consul.{{ external_domain }}'

- name: Copy Consul config
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    mode: "0600"
  notify: Restart Consul
