---
- name: Save Nomad root token
  delegate_to: localhost
  connection: local
  ansible.builtin.copy:
    content: '{{ acl_bootstrap_result.stdout }}'
    dest: '{{ playbook_dir }}/.tmp/root_token_nomad.txt'
    mode: "0644"
