---
- name: install gpg
  apt:
    name: gpg
    state: present

- name: add hashicorp apt key
  apt_key:
    url: "{{ hashicorp_gpg_url }}"
    state: present

- name: add hashicorp apt repository
  apt_repository:
    repo: "{{ hashicorp_repo }}"
    state: present
    update_cache: yes
