---
- name: Install consul-template
  ansible.builtin.apt:
    name: consul-template
    state: present

- name: Create consul-template systemd unit
  ansible.builtin.copy:
    src: consul-template.service
    dest: /lib/systemd/system/consul-template.service
    mode: "0644"

- name: Create consul-template directory
  ansible.builtin.file:
    path: /etc/consul-template.d
    state: directory
    mode: "0755"

- name: Create Vault token
  delegate_to: vault-server1
  ansible.builtin.shell:
    VAULT_TOKEN={{ lookup("file", ".tmp/root_token_vault.txt") }}
      vault token create -field=token -policy="tls-policy" -period=24h -orphan
  register: create_vault_token

- name: Copy consul-template config
  ansible.builtin.template:
    src: consul-template.hcl.j2
    dest: /etc/consul-template.d/consul-template.hcl
    mode: "0644"
  vars:
    vault_token: '{{ create_vault_token.stdout }}'
  notify: Restart consul-template

# Templates

- name: Create certs directory
  ansible.builtin.file:
    path: /opt/nomad/tls
    state: directory
    owner: nomad
    group: nomad
    mode: "0700"

- name: Create templates directory
  ansible.builtin.file:
    path: /opt/nomad/templates
    state: directory
    mode: "0755"

- name: Copy server templates
  when: certs_server | default(false)
  loop:
    - ca.crt
    - agent.crt
    - agent.key
  ansible.builtin.template:
    src: '{{ item }}.tpl.j2'
    dest: '/opt/nomad/templates/{{ item }}.tpl'
    variable_start_string: '[['
    variable_end_string: ']]'
    mode: "0644"
  notify: Restart consul-template

- name: Copy server templates config
  when: certs_server | default(false)
  loop:
    - ca.crt
    - agent.crt
    - agent.key
  ansible.builtin.template:
    src: template.hcl.j2
    dest: '/etc/consul-template.d/{{ item }}.hcl'
    mode: "0644"
  notify: Restart consul-template

- name: Copy client templates
  when: certs_client | default(false)
  loop:
    - client.crt
    - client.key
  ansible.builtin.template:
    src: '{{ item }}.tpl.j2'
    dest: '/opt/nomad/templates/{{ item }}.tpl'
    variable_start_string: '[['
    variable_end_string: ']]'
    mode: "0644"
  notify: Restart consul-template

- name: Copy client templates config
  when: certs_client | default(false)
  loop:
    - client.crt
    - client.key
  ansible.builtin.template:
    src: template.hcl.j2
    dest: '/etc/consul-template.d/{{ item }}.hcl'
    mode: "0644"
  notify: Restart consul-template
