---

- name: install nfs-common
  apt:
    name: nfs-common
    state: present

- name: add envoy apt key
  apt_key:
    url: "{{ envoy_gpg_url }}"
    state: present

- name: add envoy apt repository
  apt_repository:
    repo: "{{ envoy_repo }}"
    state: present

- name: install envoy
  apt:
    name: getenvoy-envoy
    state: present
    update_cache: yes

- name: make / shared
  become: yes
  command: mount --make-shared /

- name: make / shared at startup
  ansible.builtin.cron:
    name: make / shared at startup
    special_time: reboot
    job: mount --make-shared /

- name: add docker apt key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: add docker apt repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: copy consul resolved config
  copy:
    src: docker-dns.conf
    dest: /etc/systemd/resolved.conf.d/docker.conf
  register: resolved_config

- name: restart resolved
  when: resolved_config.changed
  service:
    name: systemd-resolved
    state: restarted

- name: copy docker daemon config
  copy:
    src: daemon.json
    dest: /etc/docker/
  register: docker_daemon_config

- name: restart docker
  when: docker_daemon_config.changed
  service:
    name: docker
    state: restarted

# - name: install openjdk
#   apt:
#     name: openjdk-17-jdk-headless
#     state: present

- name: create cni plugins directory
  file:
    path: /opt/cni/bin
    state: directory

- name: install cni plugins
  unarchive:
    src: "{{ cni_plugins_url }}"
    remote_src: yes
    dest: /opt/cni/bin/
    mode: 0755

- name: copy nomad config
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
  register: nomad_config

- name: restart nomad
  when: nomad_config.changed
  service:
    name: nomad
    state: restarted
    enabled: yes
