---
- import_role:
    name: hashicorp_apt

- name: install vault
  apt:
    name: vault
    state: present

- name: create vault directory
  file:
    path: /var/vault
    state: directory
    owner: vault
    group: vault

- name: copy vault config
  copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl
  register: vault_config

- name: restart vault
  when: vault_config.changed
  service:
    name: vault
    state: restarted
    enabled: yes
