---
- name: install prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    remote_src: yes
    dest: /usr/local/bin/
    mode: 0755
    include:
      - "{{ prometheus_archive }}/prometheus"
    extra_opts:
      - --transform
      - "s|^{{ prometheus_archive }}/prometheus$|prometheus|"

- name: create prometheus service
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: create prometheus config directory
  file:
    path: /etc/prometheus
    state: directory

- name: copy prometheus config
  copy:
    src: prometheus.yaml
    dest: /etc/prometheus/prometheus.yaml

- name: start prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes
