---
- name: Set facts
  ansible.builtin.set_fact:
    vault_token: '{{ lookup("file", ".tmp/root_token_vault.txt") }}'
    common_name: '{{ common_name | default(ansible_hostname + ".node.consul") }}'
    alt_names: '{{ (["localhost"] + (alt_names | default([]))) | join(",") }}'
    owner: '{{ owner | default("root") }}'

- name: Create certs dir
  ansible.builtin.file:
    path: '{{ certs_dir }}'
    state: directory
    owner: '{{ owner }}'
    group: '{{ owner }}'
    mode: "0700"

- name: Generate certs from Vault
  delegate_to: vault-server1
  ansible.builtin.shell:
    VAULT_TOKEN={{ vault_token }} vault write -format=json
      pki/issue/nomad-cluster
      common_name={{ common_name }}
      ttl=24h
      alt_names={{ alt_names }}
      ip_sans=127.0.0.1,{{ ansible_host }}
  register: certs

- name: Copy certs
  loop:
    - { key: certificate, file: '{{ certs_dir }}/agent.crt' }
    - { key: private_key, file: '{{ certs_dir }}/agent.crt.key' }
    - { key: issuing_ca, file: '{{ certs_dir }}/ca.crt' }
  ansible.builtin.copy:
    content: '{{ "data" | extract(certs.stdout | from_json, item.key) }}'
    dest: '{{ item.file }}'
    owner: '{{ owner }}'
    group: '{{ owner }}'
    mode: "0600"
