---
- name: 'Create private key {{ ansible_hostname }}'
  community.crypto.openssl_privatekey:
    path: '/etc/certs.d/private_key.pem'
    owner: '{{ owner | default("root") }}'
    group: '{{ owner | default("root") }}'
  register: private_key

- name: 'Create certificate signing request {{ ansible_hostname }}'
  community.crypto.openssl_csr:
    path: '/etc/certs.d/csr.pem'
    owner: '{{ owner | default("root") }}'
    group: '{{ owner | default("root") }}'
    privatekey_path: '{{ private_key.filename }}'
    subject_alt_name: '{{ alt_names }}'
    key_usage:
      - digitalSignature
      - keyEncipherment
      - dataEncipherment
    extended_key_usage:
      - serverAuth
      - clientAuth
  register: csr

- name: 'Sign certificate {{ ansible_hostname }}'
  community.crypto.x509_certificate:
    path: '/etc/certs.d/cert.pem'
    owner: '{{ owner | default("root") }}'
    group: '{{ owner | default("root") }}'
    provider: ownca
    csr_path: "{{ csr.filename }}"
    ownca_path: /etc/certs.d/ca.pem
    ownca_privatekey_content: '{{ lookup("file", ".tmp/certs/ca/private_key.pem") }}'
    ownca_not_after: "+3650d"
    ownca_not_before: "-1d"
