---
- name: create resolved directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: copy consul resolved config
  copy:
    src: consul.conf
    dest: /etc/systemd/resolved.conf.d/
  register: resolved_config

- name: restart resolved
  when: resolved_config.changed
  service:
    name: systemd-resolved
    state: restarted