---
- name: Copy Vault certs
  loop:
    - cert
    - key
  ansible.builtin.copy:
    src: '.tmp/certs/vault/{{ item }}.pem'
    dest: /etc/certs.d/
    owner: vault
    group: vault
    mode: "0600"

- name: Create Consul Vault token
  ansible.builtin.import_role:
    name: consul_token
  vars:
    token_file: /etc/vault.d/consul_token.txt
    policy_name: vault-server
    policy_rules: |
      service "vault" {
        policy = "write"
      }

- name: Read Consul Vault token
  ansible.builtin.slurp:
    path: /etc/vault.d/consul_token.txt
  register: read_consul_token

- name: Copy Vault config
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    mode: "0600"
  vars:
    vault_consul_token: '{{ read_consul_token.content | b64decode }}'
  notify: Restart Vault
