---
- name: Install Vault
  ansible.builtin.apt:
    name: vault
    state: present
    update_cache: true

- name: Create Vault certs
  ansible.builtin.import_role:
    name: certs_ownca
  vars:
    agent_name: vault
    certs_dir: /opt/vault/tls
    owner: vault
    alt_names:
      - IP:127.0.0.1
      - 'IP:{{ ansible_host }}'
      - DNS:localhost
      - DNS:vault.service.consul
      - DNS:active.vault.service.consul
      - DNS:standby.vault.service.consul
      - 'DNS:vault.{{ external_domain }}'

- name: Copy Vault CA cert
  ansible.builtin.copy:
    remote_src: true
    src: /etc/certs.d/ca.crt
    dest: /opt/vault/tls/ca.crt
    owner: vault
    group: vault
    mode: "0600"

- name: Copy Vault config
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    mode: "0600"
  notify: Restart Vault
