---
- name: Install Vault
  ansible.builtin.apt:
    name: vault
    state: present
    update_cache: true

- name: Create Vault certs
  ansible.builtin.import_role:
    name: certs_ownca
  vars:
    certs_dir: /opt/vault/tls
    owner: vault
    alt_names:
      - IP:127.0.0.1
      - 'IP:{{ ansible_host }}'
      - DNS:localhost
      - DNS:vault.service.consul
      - DNS:active.vault.service.consul
      - DNS:standby.vault.service.consul
      - 'DNS:vault.{{ external_domain }}'

- name: Create Consul Vault token
  ansible.builtin.import_role:
    name: consul_token
  vars:
    token_file: /etc/vault.d/consul_token.txt
    policy_name: vault-server
    policy_rules: |
      service "vault" {
        policy = "write"
      }

- name: Read Consul Vault token
  ansible.builtin.slurp:
    path: /etc/vault.d/consul_token.txt
  register: read_consul_token

- name: Copy Vault config
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    mode: "0600"
  vars:
    vault_consul_token: '{{ read_consul_token.content | b64decode }}'
  notify: Restart Vault
